project_id = "ivrvpbqidysrwqrthpcp"

[functions.verify-password]
verify_jwt = false

[functions.verify-session]
verify_jwt = false

[functions.update-password]
verify_jwt = false

[functions.send-magic-link]
verify_jwt = false

[functions.verify-magic-link]
verify_jwt = false
